"""add location pings

Revision ID: 3bb8fb7a3b91
Revises: 207c0ca4a050
Create Date: 2026-09-19 12:02:33.249766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bb8fb7a3b91'
down_revision: Union[str, Sequence[str], None] = '207c0ca4a050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_pings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accuracy_meters', sa.Float(), nullable=True),
    sa.Column('speed_mps', sa.Float(), nullable=True),
    sa.Column('heading_degrees', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('-180.0 <= longitude AND longitude <= 180.0', name='check_location_ping_longitude_range'),
    sa.CheckConstraint('-90.0 <= latitude AND latitude <= 90.0', name='check_location_ping_latitude_range'),
    sa.CheckConstraint('accuracy_meters IS NULL OR accuracy_meters >= 0', name='check_location_ping_accuracy_non_negative'),
    sa.CheckConstraint('heading_degrees IS NULL OR (heading_degrees >= 0 AND heading_degrees < 360)', name='check_location_ping_heading_range'),
    sa.CheckConstraint('speed_mps IS NULL OR speed_mps >= 0', name='check_location_ping_speed_non_negative'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_pings_driver_id'), 'location_pings', ['driver_id'], unique=False)
    op.create_index(op.f('ix_location_pings_recorded_at'), 'location_pings', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_location_pings_trip_id'), 'location_pings', ['trip_id'], unique=False)
    op.create_index('ix_location_pings_trip_id_recorded_at', 'location_pings', ['trip_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_location_pings_trip_id_recorded_at', table_name='location_pings')
    op.drop_index(op.f('ix_location_pings_trip_id'), table_name='location_pings')
    op.drop_index(op.f('ix_location_pings_recorded_at'), table_name='location_pings')
    op.drop_index(op.f('ix_location_pings_driver_id'), table_name='location_pings')
    op.drop_table('location_pings')
    # ### end Alembic commands ###
