"""create_buses_table_and_user_relationship

Revision ID: 3cb14e0c6b5d
Revises: 7eec8f995aa7
Create Date: 2026-09-19 11:41:22.459113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cb14e0c6b5d'
down_revision: Union[str, Sequence[str], None] = '7eec8f995aa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bus_number', sa.String(length=50), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity > 0', name='check_bus_capacity_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buses_bus_number'), 'buses', ['bus_number'], unique=True)
    op.create_index(op.f('ix_buses_registration_number'), 'buses', ['registration_number'], unique=True)
    op.add_column('users', sa.Column('assigned_bus_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_users_assigned_bus_id_buses', 'users', 'buses', ['assigned_bus_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_assigned_bus_id_buses', 'users', type_='foreignkey')
    op.drop_column('users', 'assigned_bus_id')
    op.drop_index(op.f('ix_buses_registration_number'), table_name='buses')
    op.drop_index(op.f('ix_buses_bus_number'), table_name='buses')
    op.drop_table('buses')
    # ### end Alembic commands ###
