"""add parent link requests and parent children tables

Revision ID: ad5f1f04eb65
Revises: f657f04d13d8
Create Date: 2026-09-19 12:26:11.288080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad5f1f04eb65'
down_revision: Union[str, Sequence[str], None] = 'f657f04d13d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_children',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'student_id', name='uq_parent_children_parent_student')
    )
    op.create_index(op.f('ix_parent_children_parent_id'), 'parent_children', ['parent_id'], unique=False)
    op.create_index(op.f('ix_parent_children_student_id'), 'parent_children', ['student_id'], unique=False)
    op.create_table('parent_link_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='parent_link_status_enum'), server_default='PENDING', nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_link_requests_parent_id'), 'parent_link_requests', ['parent_id'], unique=False)
    op.create_index(op.f('ix_parent_link_requests_status'), 'parent_link_requests', ['status'], unique=False)
    op.create_index(op.f('ix_parent_link_requests_student_id'), 'parent_link_requests', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parent_link_requests_student_id'), table_name='parent_link_requests')
    op.drop_index(op.f('ix_parent_link_requests_status'), table_name='parent_link_requests')
    op.drop_index(op.f('ix_parent_link_requests_parent_id'), table_name='parent_link_requests')
    op.drop_table('parent_link_requests')
    op.drop_index(op.f('ix_parent_children_student_id'), table_name='parent_children')
    op.drop_index(op.f('ix_parent_children_parent_id'), table_name='parent_children')
    op.drop_table('parent_children')
    # ### end Alembic commands ###
