"""add client_id to location_pings

Revision ID: f657f04d13d8
Revises: 3bb8fb7a3b91
Create Date: 2026-09-19 12:18:54.769673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f657f04d13d8'
down_revision: Union[str, Sequence[str], None] = '3bb8fb7a3b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location_pings', sa.Column('client_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_location_pings_client_id'), 'location_pings', ['client_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_pings_client_id'), table_name='location_pings')
    op.drop_column('location_pings', 'client_id')
    # ### end Alembic commands ###
