"""Add alerts table

Revision ID: 0c92ec1d7f93
Revises: 18d63d748f67
Create Date: 2026-09-19 12:56:47.900445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c92ec1d7f93'
down_revision: Union[str, Sequence[str], None] = '18d63d748f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('GPS_STALE', 'GPS_DISCONNECTED', 'ROUTE_DEVIATION', 'TRIP_ISSUE', 'BUS_ISSUE', 'SCHEDULE_ISSUE', 'SYSTEM', name='alerttype'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RESOLVED', name='alertstatus'), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['tracking_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_bus_id'), 'alerts', ['bus_id'], unique=False)
    op.create_index(op.f('ix_alerts_driver_id'), 'alerts', ['driver_id'], unique=False)
    op.create_index(op.f('ix_alerts_route_id'), 'alerts', ['route_id'], unique=False)
    op.create_index(op.f('ix_alerts_trip_id'), 'alerts', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_trip_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_route_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_driver_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_bus_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
