"""Add parent_student_relationships table

Revision ID: 154445c41eaf
Revises: cc17927ca8e8
Create Date: 2026-09-22 19:56:40.413075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '154445c41eaf'
down_revision: Union[str, Sequence[str], None] = 'cc17927ca8e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_student_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.Enum('FATHER', 'MOTHER', 'GUARDIAN', 'OTHER', name='relationshiptype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'REJECTED', 'REVOKED', name='relationshipstatus'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_student_relationships_parent_id'), 'parent_student_relationships', ['parent_id'], unique=False)
    op.create_index(op.f('ix_parent_student_relationships_student_id'), 'parent_student_relationships', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parent_student_relationships_student_id'), table_name='parent_student_relationships')
    op.drop_index(op.f('ix_parent_student_relationships_parent_id'), table_name='parent_student_relationships')
    op.drop_table('parent_student_relationships')
    # ### end Alembic commands ###
