"""Add route_id to Bus model

Revision ID: 18d63d748f67
Revises: 34c51a573411
Create Date: 2026-09-19 08:54:41.460973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18d63d748f67'
down_revision: Union[str, Sequence[str], None] = '34c51a573411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buses', sa.Column('route_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'buses', 'routes', ['route_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'buses', type_='foreignkey')
    op.drop_column('buses', 'route_id')
    # ### end Alembic commands ###
