"""Add parent registration requests table

Revision ID: 1bf5d248ab89
Revises: 154445c41eaf
Create Date: 2026-09-22 20:07:09.751075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '1bf5d248ab89'
down_revision: Union[str, Sequence[str], None] = '154445c41eaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_registration_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_email', sa.String(length=255), nullable=False),
    sa.Column('relationship_type', postgresql.ENUM('FATHER', 'MOTHER', 'GUARDIAN', 'OTHER', name='relationshiptype', create_type=False), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='parentrequeststatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_registration_requests_student_email'), 'parent_registration_requests', ['student_email'], unique=False)
    op.create_index(op.f('ix_parent_registration_requests_token_hash'), 'parent_registration_requests', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parent_registration_requests_token_hash'), table_name='parent_registration_requests')
    op.drop_index(op.f('ix_parent_registration_requests_student_email'), table_name='parent_registration_requests')
    op.drop_table('parent_registration_requests')
    # ### end Alembic commands ###
