"""Create Phase 2 tracking tables

Revision ID: 34c51a573411
Revises: 
Create Date: 2026-09-18 23:52:24.792815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c51a573411'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boarding_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius_meters', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('buses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bus_number', sa.String(length=30), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IDLE', 'IN_TRIP', 'MAINTENANCE', 'INACTIVE', name='busstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buses_bus_number'), 'buses', ['bus_number'], unique=True)
    op.create_index(op.f('ix_buses_registration_number'), 'buses', ['registration_number'], unique=True)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_code'), 'routes', ['code'], unique=True)
    op.create_table('driver_bus_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('assigned_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='assignmentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_bus_assignments_bus_id'), 'driver_bus_assignments', ['bus_id'], unique=False)
    op.create_index(op.f('ix_driver_bus_assignments_driver_id'), 'driver_bus_assignments', ['driver_id'], unique=False)
    op.create_table('route_stops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('boarding_point_id', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('MORNING', 'EVENING', name='routedirection'), nullable=False),
    sa.ForeignKeyConstraint(['boarding_point_id'], ['boarding_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'sequence_order', 'direction', name='uq_route_sequence_direction')
    )
    op.create_index(op.f('ix_route_stops_boarding_point_id'), 'route_stops', ['boarding_point_id'], unique=False)
    op.create_index(op.f('ix_route_stops_route_id'), 'route_stops', ['route_id'], unique=False)
    op.create_table('trip_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('direction', sa.Enum('MORNING', 'EVENING', name='routedirection'), nullable=False),
    sa.Column('days_of_week', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_schedules_bus_id'), 'trip_schedules', ['bus_id'], unique=False)
    op.create_index(op.f('ix_trip_schedules_route_id'), 'trip_schedules', ['route_id'], unique=False)
    op.create_table('tracking_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('direction', sa.Enum('MORNING', 'EVENING', name='routedirection'), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='sessionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['trip_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bus_id', 'session_date', 'schedule_id', name='uq_bus_daily_schedule_session')
    )
    op.create_index(op.f('ix_tracking_sessions_bus_id'), 'tracking_sessions', ['bus_id'], unique=False)
    op.create_index(op.f('ix_tracking_sessions_driver_id'), 'tracking_sessions', ['driver_id'], unique=False)
    op.create_index(op.f('ix_tracking_sessions_route_id'), 'tracking_sessions', ['route_id'], unique=False)
    op.create_index(op.f('ix_tracking_sessions_schedule_id'), 'tracking_sessions', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_tracking_sessions_session_date'), 'tracking_sessions', ['session_date'], unique=False)
    op.create_table('location_pings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('heading', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('server_received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['tracking_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'recorded_at', name='uq_trip_recorded_ping')
    )
    op.create_index(op.f('ix_location_pings_bus_id'), 'location_pings', ['bus_id'], unique=False)
    op.create_index(op.f('ix_location_pings_driver_id'), 'location_pings', ['driver_id'], unique=False)
    op.create_index(op.f('ix_location_pings_recorded_at'), 'location_pings', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_location_pings_trip_id'), 'location_pings', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_pings_trip_id'), table_name='location_pings')
    op.drop_index(op.f('ix_location_pings_recorded_at'), table_name='location_pings')
    op.drop_index(op.f('ix_location_pings_driver_id'), table_name='location_pings')
    op.drop_index(op.f('ix_location_pings_bus_id'), table_name='location_pings')
    op.drop_table('location_pings')
    op.drop_index(op.f('ix_tracking_sessions_session_date'), table_name='tracking_sessions')
    op.drop_index(op.f('ix_tracking_sessions_schedule_id'), table_name='tracking_sessions')
    op.drop_index(op.f('ix_tracking_sessions_route_id'), table_name='tracking_sessions')
    op.drop_index(op.f('ix_tracking_sessions_driver_id'), table_name='tracking_sessions')
    op.drop_index(op.f('ix_tracking_sessions_bus_id'), table_name='tracking_sessions')
    op.drop_table('tracking_sessions')
    op.drop_index(op.f('ix_trip_schedules_route_id'), table_name='trip_schedules')
    op.drop_index(op.f('ix_trip_schedules_bus_id'), table_name='trip_schedules')
    op.drop_table('trip_schedules')
    op.drop_index(op.f('ix_route_stops_route_id'), table_name='route_stops')
    op.drop_index(op.f('ix_route_stops_boarding_point_id'), table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_index(op.f('ix_driver_bus_assignments_driver_id'), table_name='driver_bus_assignments')
    op.drop_index(op.f('ix_driver_bus_assignments_bus_id'), table_name='driver_bus_assignments')
    op.drop_table('driver_bus_assignments')
    op.drop_index(op.f('ix_routes_code'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_buses_registration_number'), table_name='buses')
    op.drop_index(op.f('ix_buses_bus_number'), table_name='buses')
    op.drop_table('buses')
    op.drop_table('boarding_points')
    # ### end Alembic commands ###
