"""Add phone_number to user

Revision ID: 975649f49de1
Revises: f5eaaf12eaa4
Create Date: 2026-09-19 23:28:05.070240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '975649f49de1'
down_revision: Union[str, Sequence[str], None] = 'f5eaaf12eaa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boarding_points', sa.Column('route_geometry', sa.JSON(), nullable=True))
    op.add_column('routes', sa.Column('route_geometry', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.drop_column('routes', 'route_geometry')
    op.drop_column('boarding_points', 'route_geometry')
    # ### end Alembic commands ###
