"""Add student_bus_assignments table

Revision ID: cc17927ca8e8
Revises: 975649f49de1
Create Date: 2026-09-20 00:26:26.387248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc17927ca8e8'
down_revision: Union[str, Sequence[str], None] = '975649f49de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_bus_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('assigned_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='studentassignmentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_student_bus_active', 'student_bus_assignments', ['student_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_index(op.f('ix_student_bus_assignments_bus_id'), 'student_bus_assignments', ['bus_id'], unique=False)
    op.create_index(op.f('ix_student_bus_assignments_student_id'), 'student_bus_assignments', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_bus_assignments_student_id'), table_name='student_bus_assignments')
    op.drop_index(op.f('ix_student_bus_assignments_bus_id'), table_name='student_bus_assignments')
    op.drop_index('ix_student_bus_active', table_name='student_bus_assignments', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_table('student_bus_assignments')
    # ### end Alembic commands ###
