"""Add emergencies table

Revision ID: f5eaaf12eaa4
Revises: 0c92ec1d7f93
Create Date: 2026-09-19 13:00:59.135551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5eaaf12eaa4'
down_revision: Union[str, Sequence[str], None] = '0c92ec1d7f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('MANUAL_SOS', 'AUTOMATIC_ACCIDENT', name='emergencytype'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', name='emergencyseverity'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', name='emergencystatus'), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['tracking_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergencies_bus_id'), 'emergencies', ['bus_id'], unique=False)
    op.create_index(op.f('ix_emergencies_driver_id'), 'emergencies', ['driver_id'], unique=False)
    op.create_index(op.f('ix_emergencies_route_id'), 'emergencies', ['route_id'], unique=False)
    op.create_index(op.f('ix_emergencies_trip_id'), 'emergencies', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emergencies_trip_id'), table_name='emergencies')
    op.drop_index(op.f('ix_emergencies_route_id'), table_name='emergencies')
    op.drop_index(op.f('ix_emergencies_driver_id'), table_name='emergencies')
    op.drop_index(op.f('ix_emergencies_bus_id'), table_name='emergencies')
    op.drop_table('emergencies')
    # ### end Alembic commands ###
